GET http://localhost:8000/movies

### Get a movie by id

GET http://localhost:8000/movies/2

### Create a movie


POST http://localhost:8000/movies
Content-Type: application/json

{
  "isbn": "33",
  "title": "The Matrix",
  "director": {
    "firstname": "Lana",
    "lastname": "Wachowski"
  }
}

### Update a movie
PUT http://localhost:8000/movies/401413
Content-Type: application/json

{
  "isbn": "33",
  "title": "Matrix Returns",
  "director": {
    "firstname": "Lana",
    "lastname": "Wachowski"
  }
}
### Update a movie
DELETE http://localhost:8000/movies/777754


